//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuayThuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThu
    {
        public int Id_DoanhThu { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> DoanhThuBan { get; set; }
        public Nullable<int> TienNhapHang { get; set; }
        public Nullable<int> ThuChiKhac { get; set; }
        public string GhiChu { get; set; }
    }
}
