//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuayThuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public int Id_DonHang { get; set; }
        public int Id_SanPham { get; set; }
        public int Id_KhoHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> GiamGia { get; set; }
        public Nullable<int> TongTien { get; set; }
        public int Id_NhanVien { get; set; }
        public Nullable<int> Id_Order { get; set; }
    
        public virtual KhoHang KhoHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
