//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuayThuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonVi
    {
        public int Id_DonVi { get; set; }
        public string DonVi1 { get; set; }
    }
}
