//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuayThuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id_Order { get; set; }
        public string MaGiaoDich { get; set; }
        public string TenKhachHang { get; set; }
        public string LienHe { get; set; }
        public string DiaChi { get; set; }
        public string PhuongThucTT { get; set; }
        public string TrangThai { get; set; }
        public int Id_NhanVien { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
