//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuayThuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamNhap
    {
        public int Id_SanPhamNhap { get; set; }
        public string MaHoaDon { get; set; }
        public Nullable<int> Id_SanPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> GiaNhap { get; set; }
        public Nullable<int> GiamGia { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
